
name: Email on Commit
on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    environment: env

    steps:
    - name: Send greeting
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "Novo commit no repositório ${{ github.repository }}"
        to: matheusfrancisco1103@gmail.com
        from: GitHub Bot <${{ secrets.EMAIL_USER }}>
        body: |
          Olá,

          Um novo commit foi realizado.

          Autor: ${{ github.actor }}
          Repositório: ${{ github.repository }}
          Branch: ${{ github.ref_name }}

          Mensagem:
          ${{ github.event.head_commit.message }}

          Commit:
          ${{ github.event.head_commit.url }}
